"""add mitre metadata fields to vulnerabilities

Revision ID: 684afb0c8c71
Revises: 90a34578c5c1
Create Date: 2026-07-09 22:31:42.930537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684afb0c8c71'
down_revision: Union[str, Sequence[str], None] = '90a34578c5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('cve_state', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('assigner_org', sa.String(length=255), nullable=True))
    op.add_column('vulnerabilities', sa.Column('date_reserved', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'date_reserved')
    op.drop_column('vulnerabilities', 'assigner_org')
    op.drop_column('vulnerabilities', 'cve_state')
    # ### end Alembic commands ###
