"""add redhat enrichment fields to vulnerabilities

Revision ID: 837408e55466
Revises: 684afb0c8c71
Create Date: 2026-07-09 22:38:21.324947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837408e55466'
down_revision: Union[str, Sequence[str], None] = '684afb0c8c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('redhat_severity', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('redhat_statement', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'redhat_statement')
    op.drop_column('vulnerabilities', 'redhat_severity')
    # ### end Alembic commands ###
