"""add kev enrichment fields to vulnerabilities

Revision ID: 90a34578c5c1
Revises: 39d8703ff0b5
Create Date: 2026-07-09 22:20:21.420485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a34578c5c1'
down_revision: Union[str, Sequence[str], None] = '39d8703ff0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'vulnerabilities',
        sa.Column('is_known_exploited', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('vulnerabilities', sa.Column('kev_date_added', sa.Date(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('kev_due_date', sa.Date(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('ransomware_campaign_use', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'ransomware_campaign_use')
    op.drop_column('vulnerabilities', 'kev_due_date')
    op.drop_column('vulnerabilities', 'kev_date_added')
    op.drop_column('vulnerabilities', 'is_known_exploited')
    # ### end Alembic commands ###
