"""create advisories table

Revision ID: 9d684da259bc
Revises: 905078e87c24
Create Date: 2026-07-10 15:59:08.964653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d684da259bc'
down_revision: Union[str, Sequence[str], None] = '905078e87c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('advisory_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cve_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_advisories_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advisories'))
    )
    op.create_index(op.f('ix_advisories_advisory_id'), 'advisories', ['advisory_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisories_advisory_id'), table_name='advisories')
    op.drop_table('advisories')
    # ### end Alembic commands ###
